version: '3'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - local-net
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=leaderboard
    networks:
      - local-net
  app:
    image: leaderboards
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - local-net
networks:
  local-net:
    driver: bridge